### ISSUE TITLE
Generated content in a subdirectory

### ISSUE THREAD

**Issue by MikeRankin** [DevWurm/webpack-war-plugin#10]
How do I make the generated content appear in a subdirectory in the war archive such as /static?

**Comment by DevWurm** [comment]
The plugin bundles exactly the file tree wich is emitted by Webpack into the output folder. So you can use the [Webpack `output` configuration](https://webpack.js.org/configuration/output/) to manage the file structure inside the output directory ([example](https://stackoverflow.com/questions/31718908/webpack-output-files-to-different-directories)).

**Comment by MikeRankin** [comment]
Thanks! I got it to work the way I like.  It took me forever to realize that you have to put the subdirectory in the filename attribute and not as part of the path.  The example you provided clued me in.

**Comment by DevWurm** [comment]
That is basically a Webpack behavior and not related to the Plugin itself ;)
(I guess you refer to the latest edit of the answer?)
