### ISSUE TITLE
Question: option to choose jar/war

### ISSUE THREAD

**Issue by nikolaylagutko** [DevWurm/webpack-war-plugin#7]
Does it make sense to add additional option to choose between jar and war archive? In face there is no difference (except file extension) between these two types, but for my deployment pipeline I need jar-file so I need to rename it manually. 
So the question is - will it be useful to add such option in configuration of this plugin?

**Comment by DevWurm** [comment]
Hey, thank you for your kind request :)

The plugin already does respect a self specified extension (or it should at least).
If you specify an `archiveName` with an extension, it should respect that extension.

Feel free to comment again, if it doesn't work ;)
